version: '3'

services:

  nginx:
    image: nginx:alpine
    restart: always
    container_name: ${PROJECT_NAME}_nginx
    environment:
      TZ: Europe/Moscow
    volumes:
      - ./:/var/www/${PROJECT_NAME}/site
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    networks:
      - common
    ports:
      - ${PROJECT_PORT}:80

  mysql:
    image: mysql:8
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/99-overrides.cnf
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/bak/:/bak
    ports:
      - ${PROJECT_DB_PORT}:3306
    networks:
      - common

  php-fpm:
    build: ./docker/php
    container_name: ${PROJECT_NAME}_php-fpm
    restart: always
    working_dir: /var/www/${PROJECT_NAME}/site
    environment:
      TZ: Europe/Moscow
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/${PROJECT_NAME}/site
    networks:
      - common

  redis:
    image: redis
    container_name: ${PROJECT_NAME}_redis
    environment:
      TZ: Europe/Moscow
    networks:
      - common


networks:
  common:
    external: true
